### ISSUE TITLE
Training script for the transformer

### ISSUE THREAD

**Issue by kangaroo42** [huangnengCSU/SACall-basecaller#1]
I was wondering if there might be a separate script to train the transformer model as defined by `Transformer` in `./transformer/modules.py`? Something similar to `./ctc_train.py`. 

Many thanks in advance!

**Comment by huangnengCSU** [comment]
To kangaroo42,
We didn't train the transformer Encoder in SACall separately. We trained SACall (transformer encoder + CTC) as an end-to-end model, whose input is the raw signal, and the output is the DNA sequence.
Neng

**Comment by kangaroo42** [comment]
Understood. Thanks for making the code available for the transformer module nevertheless!
