### ISSUE TITLE
Fasta file after basecalling empty

### ISSUE THREAD

**Issue by monikaheinzl** [huangnengCSU/SACall-basecaller#2]
Hi, 
I am interested in using your basecaller. I have trained it with my own data but in the basecalling step the produced fasta file is still empty afterwards. 

I found out that there is an issue in the decoder step of the ctcdecode module because the variable `seq_lens`, which is retrieved by the `decode` function of your class `BeamCTCDecoder` in the script ctc_decoder.py (line 130), contains only zeros. This variable you use then in the `convert_to_strings` function in the same class which causes that the decoded sequence is empty. Can you help me with this issue?

Many thanks,
Monika

**Comment by huangnengCSU** [comment]
To Monika:
    Thanks for your feedback. In ctc_decoder.py(line 130), the variable `sizes` should be like `tensor([512, 512, 512,  ..., 512, 512, 415], dtype=torch.int32)` and the variable `seq_lens` should be greater than zeros. Firstly, you check if a raw signal fast5 file only contains one read instead of multiple reads. Second, you run the command `python generate_dataset/inference_data.py -fast5 ${fast5_dir} -records_dir ${tmp_records_dir} -raw_len ${signal_window_length}`. Then you randomly pick one file from the `${tmp_records_dir}` and read it by `numpy.load()` to know the shape of the array. If there is no problem, the shape of array should be `[n,2048,1]`.
Neng

**Comment by monikaheinzl** [comment]
Thank you for your fast answer!

I have checked the files in the `${tmp_records_dir}` directory and they all have shape `[n,2048,1]`.
Everything seems to be fine until the decoding step in line 130. Because the input variables `probs` and `lengths` for the function where you call the decoder (line 173 in script call.py) seem to be fine. `probs` has the shape `[718, 512, 6]` and `lengths` is a tensor like you mentioned `tensor([512, 512, 512, ..., 512, 512, 415], dtype=torch.int32) `.

But the variable `out` from the ctcdecode package contains values that are huge (in the range of +/- 1 billion). Should this be correct? I guess this variable should contain the predicted classes.

**Update:**
The decoding step works if I set the parameter `cutoff_top_n` to `6` (instead of `0`, line 171 in call.py) like in the ctc_train.py script. Is this a proper solution for my problem?

**Comment by monikaheinzl** [comment]
Sorry again, but which version of the package ctcdecode did you use? 

I guess I have the same issue as described here:
https://github.com/parlance/ctcdecode/issues/168

**Comment by huangnengCSU** [comment]
To Monika:
    I am using the `ctcdecode v0.4`. I think the problem is due to the bug in `ctcdecode` package. The parameter `cutoff_top_n=0` means don't cut anything. If you can fix the bug by setting the parameter `cutoff_top_n` to `6`, that is good. And I think this modification will not have much negative effect on the result.

Neng

**Comment by monikaheinzl** [comment]
Ok, thank you. I have one more question:

About one third of my reads are not basecalled because of the preprocessing step. In the `inference_data.py` script are two if-statements which cause the filtering:
`if len(trimed_raw) / len(raw) < 0.6` and `if len(trimed_raw) == 0`

What is trimmed from the reads and why is this needed?

**Comment by huangnengCSU** [comment]
The signals at both ends are those produced by the absence of bases in the nanopore or by DNA blocking. And we assume that if there are too many of such signals, the raw data is low quality. But you can modify the threshold `0.6` to improve the throughout of basecalling.

**Comment by monikaheinzl** [comment]
And how do you infer that there are such signals at both ends? Unfortunately, I could not find anything to that in your publication.

**Comment by huangnengCSU** [comment]
This step of cutting off the signals at both ends is similar to ONT basecallers such as Scrappie, but I've added that if the cut-outs are too much, the raw signal will not be basecalled. This is not mentioned in the paper.
