### ISSUE TITLE
你好，请问你在论文中所使用的数据集可以分享一下吗？我自己处理的数据现在按照你提供的方法训练会出现loss会出现Nan，不清楚是由于我数据处理问题还是框架版本不一致引起的，我想比对一下。谢谢

### ISSUE THREAD

**Issue by wenyu332** [huangnengCSU/SACall-basecaller#3]

**Comment by huangnengCSU** [comment]
@wenyu332 
    你好，训练出现Nan的原因可能是因为target序列的长度比input的长度更长导致的。你需要过滤掉训练数据中的这种例子
    例如 label='abbbccddddcccaa'，标签序列的长度为15，ctc计算时会在连续字符间插入blank，以及在首尾插入blank。blank插入情况为 -ab-b-bc-cd-d-d-dc-c-ca-a-。总的target_length=15+11 = 26. 算上blank以后的target length 小于 input length的样本才是符合要求的，否则会导致loss为inf。
    另外，原始数据的链接在：https://bridges.monash.edu/authors/Ryan_Wick/6246767

**Comment by wenyu332** [comment]
感谢回复！我看了链接中的数据集，有一个Training data,大小为110G，里面包含了training_fast5s和validation_fast5s文件，里面有50个文件，您论文中是用的这个数据集挑选了其中的10个吗？然后按照论文中描述的处理方法生成npy文件用来训练？

**Comment by huangnengCSU** [comment]
@wenyu332 
数据集是该链接中提供的50个物种的数据，我记得是每个物种随机选择了1/10的数据，然后将50个物种随机选出的数据合并。因为使用所有数据的话太大了。

**Comment by wenyu332** [comment]
那个里面只有训练集和验证集，没有测试集，您是把验证集的结果作为最终的论文报告结果吗？

**Comment by huangnengCSU** [comment]
@wenyu332 
测试集还有10个物种，与训练的50个物种不同。测试集物种：
原始信号：https://bridges.monash.edu/articles/dataset/Raw_fast5s/7676174
参考序列：https://bridges.monash.edu/articles/dataset/Assemblies/7676156

关于数据集，请参考论文
Wick R R, Judd L M, Holt K E. Performance of neural network basecalling tools for Oxford Nanopore sequencing[J]. Genome biology, 2019, 20(1): 1-10.

**Comment by wenyu332** [comment]
好的，感谢这么多次的回复！  我自己去尝试一下，后面有问题还得麻烦您。。。谢谢！

**Comment by wenyu332** [comment]
你好，请问有最终验证测试集准确率的脚本吗，我在代码中的scripts找到一个analysis.sh文件，请问是这个吗？ 我是先执行的run_caller.sh脚本进行basecalling，执行analysis.sh发现报错了，自己修改也没成功，所以请教一下。谢谢。

**Comment by huangnengCSU** [comment]
@wenyu332 
`analysis.sh`不是评估的脚本，论文实验评估脚本在`scripts/KP_dataset_error_report`路径下。我重新整理了评估脚本`error_rate.sh`如下：
```
#!/bin/bash
reference=$1
basecalled_file=$2

minimap2 -ax map-ont ${reference} ${basecalled_file} --eqx -t 40 > aln.sam
python minimap2_alignment_report.py aln.sam > error.sketch
python read_sketch.py error.sketch error_report.txt
```
!!! 注意确保minimap2_alignment_report.py和read_sketch.py两个文件的路径准确，`minimap2_alignment_report.py`在路径`scripts/`，`read_sketch.py`在路径`scripts/KP_dataset_error_report`
生成结果的五项分别表示['match','deletion','insertion','mismatch','error rate']。

举个栗子：
```
user@ubuntu:~/data/ecoli$ bash error_rate.sh GCF_000005845.2_ASM584v2_genomic.fna call.fastq
[M::mm_idx_gen::0.265*0.70] collected minimizers
[M::mm_idx_gen::0.310*2.28] sorted minimizers
[M::main::0.310*2.28] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.335*2.19] mid_occ = 12
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.352*2.13] distinct minimizers: 838542 (98.18% are singletons); average occurrences: 1.034; average spacing: 5.352; total length: 4641652
[M::worker_pipeline::12.998*32.88] mapped 55058 sequences
[M::worker_pipeline::18.499*31.31] mapped 52745 sequences
[M::worker_pipeline::23.662*29.62] mapped 48032 sequences
[M::worker_pipeline::24.270*28.90] mapped 8637 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -ax map-ont --eqx -t 40 GCF_000005845.2_ASM584v2_genomic.fna call.fastq
[M::main] Real time: 24.449 sec; CPU: 701.679 sec; Peak RSS: 5.233 GB
[0.9196457190648222, 0.037333879172353555, 0.05762755448734829, 0.04302040176280557, 0.13798183542250847]

```

**Comment by wenyu332** [comment]
@huangnengCSU 感谢感谢，太麻烦你了，我自己在试试。谢谢！

**Comment by wenyu332** [comment]
你好，还有一个问题，我看到wick论文中有两个评价指标：consensus identity和Read identity,您在论文中使用的是Read identity吗？

**Comment by huangnengCSU** [comment]
@wenyu332 
read identity和consensus identity都用了，read identity是basecall reads的精度(Fig.3)，consensus identity是assembly+polishing以后组装结果的精度，对应论文中Fig.4

**Comment by wenyu332** [comment]
@huangnengCSU  read identity

> @wenyu332
> `analysis.sh`不是评估的脚本，论文实验评估脚本在`scripts/KP_dataset_error_report`路径下。我重新整理了评估脚本`error_rate.sh`如下：
> 
> ```
> #!/bin/bash
> reference=$1
> basecalled_file=$2
> 
> minimap2 -ax map-ont ${reference} ${basecalled_file} --eqx -t 40 > aln.sam
> python minimap2_alignment_report.py aln.sam > error.sketch
> python read_sketch.py error.sketch error_report.txt
> ```
> 
> !!! 注意确保minimap2_alignment_report.py和read_sketch.py两个文件的路径准确，`minimap2_alignment_report.py`在路径`scripts/`，`read_sketch.py`在路径`scripts/KP_dataset_error_report`
> 生成结果的五项分别表示['match','deletion','insertion','mismatch','error rate']。
> 
> 举个栗子：
> 
> ```
> user@ubuntu:~/data/ecoli$ bash error_rate.sh GCF_000005845.2_ASM584v2_genomic.fna call.fastq
> [M::mm_idx_gen::0.265*0.70] collected minimizers
> [M::mm_idx_gen::0.310*2.28] sorted minimizers
> [M::main::0.310*2.28] loaded/built the index for 1 target sequence(s)
> [M::mm_mapopt_update::0.335*2.19] mid_occ = 12
> [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
> [M::mm_idx_stat::0.352*2.13] distinct minimizers: 838542 (98.18% are singletons); average occurrences: 1.034; average spacing: 5.352; total length: 4641652
> [M::worker_pipeline::12.998*32.88] mapped 55058 sequences
> [M::worker_pipeline::18.499*31.31] mapped 52745 sequences
> [M::worker_pipeline::23.662*29.62] mapped 48032 sequences
> [M::worker_pipeline::24.270*28.90] mapped 8637 sequences
> [M::main] Version: 2.17-r974-dirty
> [M::main] CMD: minimap2 -ax map-ont --eqx -t 40 GCF_000005845.2_ASM584v2_genomic.fna call.fastq
> [M::main] Real time: 24.449 sec; CPU: 701.679 sec; Peak RSS: 5.233 GB
> [0.9196457190648222, 0.037333879172353555, 0.05762755448734829, 0.04302040176280557, 0.13798183542250847]
> ```
也就是说这个脚本输出的0.919645719064822 是read identity指标，而'deletion','insertion','mismatch'这三个指标的和为最后一列的error rate，用1-error rate就是consensus identity，是这样理解吗？
